/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonIdRouteImport } from './routes/salon.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonIdRoute = SalonIdRouteImport.update({
  id: '/salon/$id',
  path: '/salon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/salon/$id': typeof SalonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/salon/$id': typeof SalonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/salon/$id': typeof SalonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/investors'
    | '/journey'
    | '/matchmaker'
    | '/membership'
    | '/partners'
    | '/profile'
    | '/salon/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/investors'
    | '/journey'
    | '/matchmaker'
    | '/membership'
    | '/partners'
    | '/profile'
    | '/salon/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/investors'
    | '/journey'
    | '/matchmaker'
    | '/membership'
    | '/partners'
    | '/profile'
    | '/salon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  InvestorsRoute: typeof InvestorsRoute
  JourneyRoute: typeof JourneyRoute
  MatchmakerRoute: typeof MatchmakerRoute
  MembershipRoute: typeof MembershipRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  SalonIdRoute: typeof SalonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$id': {
      id: '/salon/$id'
      path: '/salon/$id'
      fullPath: '/salon/$id'
      preLoaderRoute: typeof SalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  InvestorsRoute: InvestorsRoute,
  JourneyRoute: JourneyRoute,
  MatchmakerRoute: MatchmakerRoute,
  MembershipRoute: MembershipRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  SalonIdRoute: SalonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
